################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Middlewares/Third_Party/LoRaWAN/Mac/LoRaMac.c \
/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Middlewares/Third_Party/LoRaWAN/Mac/LoRaMacAdr.c \
/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Middlewares/Third_Party/LoRaWAN/Mac/LoRaMacClassB.c \
/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Middlewares/Third_Party/LoRaWAN/Mac/LoRaMacCommands.c \
/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Middlewares/Third_Party/LoRaWAN/Mac/LoRaMacConfirmQueue.c \
/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Middlewares/Third_Party/LoRaWAN/Mac/LoRaMacCrypto.c \
/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Middlewares/Third_Party/LoRaWAN/Mac/LoRaMacFCntHandler.c \
/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Middlewares/Third_Party/LoRaWAN/Mac/LoRaMacParser.c \
/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Middlewares/Third_Party/LoRaWAN/Mac/LoRaMacSerializer.c 

OBJS += \
./Middlewares/LoRaWAN/Mac/LoRaMac.o \
./Middlewares/LoRaWAN/Mac/LoRaMacAdr.o \
./Middlewares/LoRaWAN/Mac/LoRaMacClassB.o \
./Middlewares/LoRaWAN/Mac/LoRaMacCommands.o \
./Middlewares/LoRaWAN/Mac/LoRaMacConfirmQueue.o \
./Middlewares/LoRaWAN/Mac/LoRaMacCrypto.o \
./Middlewares/LoRaWAN/Mac/LoRaMacFCntHandler.o \
./Middlewares/LoRaWAN/Mac/LoRaMacParser.o \
./Middlewares/LoRaWAN/Mac/LoRaMacSerializer.o 

C_DEPS += \
./Middlewares/LoRaWAN/Mac/LoRaMac.d \
./Middlewares/LoRaWAN/Mac/LoRaMacAdr.d \
./Middlewares/LoRaWAN/Mac/LoRaMacClassB.d \
./Middlewares/LoRaWAN/Mac/LoRaMacCommands.d \
./Middlewares/LoRaWAN/Mac/LoRaMacConfirmQueue.d \
./Middlewares/LoRaWAN/Mac/LoRaMacCrypto.d \
./Middlewares/LoRaWAN/Mac/LoRaMacFCntHandler.d \
./Middlewares/LoRaWAN/Mac/LoRaMacParser.d \
./Middlewares/LoRaWAN/Mac/LoRaMacSerializer.d 


# Each subdirectory must supply rules for building sources it contributes
Middlewares/LoRaWAN/Mac/LoRaMac.o: /home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Middlewares/Third_Party/LoRaWAN/Mac/LoRaMac.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m0plus -mthumb -mfloat-abi=soft -DSTM32L073xx -DUSE_STM32L0XX_NUCLEO -DUSE_HAL_DRIVER -DREGION_EU868 -DGXX_EXPERIMENTAL_CXX0X -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Projects/STM32L073RZ-Nucleo/Applications/LoRa/End_Node/Core/inc" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Projects/STM32L073RZ-Nucleo/Applications/LoRa/End_Node/LoRaWAN/App/inc" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/BSP/STM32L0xx_Nucleo" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/STM32L0xx_HAL_Driver/Inc" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/CMSIS/Device/ST/STM32L0xx/Include" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/CMSIS/Include" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Middlewares/Third_Party/LoRaWAN/Crypto" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Middlewares/Third_Party/LoRaWAN/Mac" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Middlewares/Third_Party/LoRaWAN/Phy" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Middlewares/Third_Party/LoRaWAN/Utilities" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Middlewares/Third_Party/LoRaWAN/Core" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/BSP/Components/Common" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/BSP/Components/hts221" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/BSP/Components/lps22hb" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/BSP/Components/lps25hb" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/BSP/Components/sx1272" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/BSP/X_NUCLEO_IKS01A1" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/BSP/X_NUCLEO_IKS01A2" -I../../../../../../../../Drivers/BSP/sx1272mb2das  -Os -g3 -Wall -fmessage-length=0 -std=c++11 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Middlewares/LoRaWAN/Mac/LoRaMacAdr.o: /home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Middlewares/Third_Party/LoRaWAN/Mac/LoRaMacAdr.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m0plus -mthumb -mfloat-abi=soft -DSTM32L073xx -DUSE_STM32L0XX_NUCLEO -DUSE_HAL_DRIVER -DREGION_EU868 -DGXX_EXPERIMENTAL_CXX0X -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Projects/STM32L073RZ-Nucleo/Applications/LoRa/End_Node/Core/inc" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Projects/STM32L073RZ-Nucleo/Applications/LoRa/End_Node/LoRaWAN/App/inc" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/BSP/STM32L0xx_Nucleo" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/STM32L0xx_HAL_Driver/Inc" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/CMSIS/Device/ST/STM32L0xx/Include" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/CMSIS/Include" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Middlewares/Third_Party/LoRaWAN/Crypto" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Middlewares/Third_Party/LoRaWAN/Mac" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Middlewares/Third_Party/LoRaWAN/Phy" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Middlewares/Third_Party/LoRaWAN/Utilities" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Middlewares/Third_Party/LoRaWAN/Core" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/BSP/Components/Common" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/BSP/Components/hts221" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/BSP/Components/lps22hb" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/BSP/Components/lps25hb" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/BSP/Components/sx1272" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/BSP/X_NUCLEO_IKS01A1" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/BSP/X_NUCLEO_IKS01A2" -I../../../../../../../../Drivers/BSP/sx1272mb2das  -Os -g3 -Wall -fmessage-length=0 -std=c++11 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Middlewares/LoRaWAN/Mac/LoRaMacClassB.o: /home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Middlewares/Third_Party/LoRaWAN/Mac/LoRaMacClassB.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m0plus -mthumb -mfloat-abi=soft -DSTM32L073xx -DUSE_STM32L0XX_NUCLEO -DUSE_HAL_DRIVER -DREGION_EU868 -DGXX_EXPERIMENTAL_CXX0X -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Projects/STM32L073RZ-Nucleo/Applications/LoRa/End_Node/Core/inc" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Projects/STM32L073RZ-Nucleo/Applications/LoRa/End_Node/LoRaWAN/App/inc" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/BSP/STM32L0xx_Nucleo" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/STM32L0xx_HAL_Driver/Inc" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/CMSIS/Device/ST/STM32L0xx/Include" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/CMSIS/Include" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Middlewares/Third_Party/LoRaWAN/Crypto" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Middlewares/Third_Party/LoRaWAN/Mac" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Middlewares/Third_Party/LoRaWAN/Phy" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Middlewares/Third_Party/LoRaWAN/Utilities" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Middlewares/Third_Party/LoRaWAN/Core" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/BSP/Components/Common" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/BSP/Components/hts221" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/BSP/Components/lps22hb" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/BSP/Components/lps25hb" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/BSP/Components/sx1272" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/BSP/X_NUCLEO_IKS01A1" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/BSP/X_NUCLEO_IKS01A2" -I../../../../../../../../Drivers/BSP/sx1272mb2das  -Os -g3 -Wall -fmessage-length=0 -std=c++11 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Middlewares/LoRaWAN/Mac/LoRaMacCommands.o: /home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Middlewares/Third_Party/LoRaWAN/Mac/LoRaMacCommands.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m0plus -mthumb -mfloat-abi=soft -DSTM32L073xx -DUSE_STM32L0XX_NUCLEO -DUSE_HAL_DRIVER -DREGION_EU868 -DGXX_EXPERIMENTAL_CXX0X -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Projects/STM32L073RZ-Nucleo/Applications/LoRa/End_Node/Core/inc" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Projects/STM32L073RZ-Nucleo/Applications/LoRa/End_Node/LoRaWAN/App/inc" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/BSP/STM32L0xx_Nucleo" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/STM32L0xx_HAL_Driver/Inc" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/CMSIS/Device/ST/STM32L0xx/Include" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/CMSIS/Include" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Middlewares/Third_Party/LoRaWAN/Crypto" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Middlewares/Third_Party/LoRaWAN/Mac" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Middlewares/Third_Party/LoRaWAN/Phy" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Middlewares/Third_Party/LoRaWAN/Utilities" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Middlewares/Third_Party/LoRaWAN/Core" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/BSP/Components/Common" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/BSP/Components/hts221" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/BSP/Components/lps22hb" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/BSP/Components/lps25hb" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/BSP/Components/sx1272" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/BSP/X_NUCLEO_IKS01A1" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/BSP/X_NUCLEO_IKS01A2" -I../../../../../../../../Drivers/BSP/sx1272mb2das  -Os -g3 -Wall -fmessage-length=0 -std=c++11 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Middlewares/LoRaWAN/Mac/LoRaMacConfirmQueue.o: /home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Middlewares/Third_Party/LoRaWAN/Mac/LoRaMacConfirmQueue.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m0plus -mthumb -mfloat-abi=soft -DSTM32L073xx -DUSE_STM32L0XX_NUCLEO -DUSE_HAL_DRIVER -DREGION_EU868 -DGXX_EXPERIMENTAL_CXX0X -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Projects/STM32L073RZ-Nucleo/Applications/LoRa/End_Node/Core/inc" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Projects/STM32L073RZ-Nucleo/Applications/LoRa/End_Node/LoRaWAN/App/inc" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/BSP/STM32L0xx_Nucleo" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/STM32L0xx_HAL_Driver/Inc" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/CMSIS/Device/ST/STM32L0xx/Include" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/CMSIS/Include" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Middlewares/Third_Party/LoRaWAN/Crypto" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Middlewares/Third_Party/LoRaWAN/Mac" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Middlewares/Third_Party/LoRaWAN/Phy" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Middlewares/Third_Party/LoRaWAN/Utilities" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Middlewares/Third_Party/LoRaWAN/Core" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/BSP/Components/Common" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/BSP/Components/hts221" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/BSP/Components/lps22hb" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/BSP/Components/lps25hb" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/BSP/Components/sx1272" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/BSP/X_NUCLEO_IKS01A1" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/BSP/X_NUCLEO_IKS01A2" -I../../../../../../../../Drivers/BSP/sx1272mb2das  -Os -g3 -Wall -fmessage-length=0 -std=c++11 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Middlewares/LoRaWAN/Mac/LoRaMacCrypto.o: /home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Middlewares/Third_Party/LoRaWAN/Mac/LoRaMacCrypto.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m0plus -mthumb -mfloat-abi=soft -DSTM32L073xx -DUSE_STM32L0XX_NUCLEO -DUSE_HAL_DRIVER -DREGION_EU868 -DGXX_EXPERIMENTAL_CXX0X -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Projects/STM32L073RZ-Nucleo/Applications/LoRa/End_Node/Core/inc" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Projects/STM32L073RZ-Nucleo/Applications/LoRa/End_Node/LoRaWAN/App/inc" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/BSP/STM32L0xx_Nucleo" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/STM32L0xx_HAL_Driver/Inc" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/CMSIS/Device/ST/STM32L0xx/Include" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/CMSIS/Include" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Middlewares/Third_Party/LoRaWAN/Crypto" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Middlewares/Third_Party/LoRaWAN/Mac" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Middlewares/Third_Party/LoRaWAN/Phy" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Middlewares/Third_Party/LoRaWAN/Utilities" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Middlewares/Third_Party/LoRaWAN/Core" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/BSP/Components/Common" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/BSP/Components/hts221" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/BSP/Components/lps22hb" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/BSP/Components/lps25hb" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/BSP/Components/sx1272" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/BSP/X_NUCLEO_IKS01A1" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/BSP/X_NUCLEO_IKS01A2" -I../../../../../../../../Drivers/BSP/sx1272mb2das  -Os -g3 -Wall -fmessage-length=0 -std=c++11 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Middlewares/LoRaWAN/Mac/LoRaMacFCntHandler.o: /home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Middlewares/Third_Party/LoRaWAN/Mac/LoRaMacFCntHandler.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m0plus -mthumb -mfloat-abi=soft -DSTM32L073xx -DUSE_STM32L0XX_NUCLEO -DUSE_HAL_DRIVER -DREGION_EU868 -DGXX_EXPERIMENTAL_CXX0X -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Projects/STM32L073RZ-Nucleo/Applications/LoRa/End_Node/Core/inc" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Projects/STM32L073RZ-Nucleo/Applications/LoRa/End_Node/LoRaWAN/App/inc" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/BSP/STM32L0xx_Nucleo" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/STM32L0xx_HAL_Driver/Inc" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/CMSIS/Device/ST/STM32L0xx/Include" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/CMSIS/Include" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Middlewares/Third_Party/LoRaWAN/Crypto" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Middlewares/Third_Party/LoRaWAN/Mac" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Middlewares/Third_Party/LoRaWAN/Phy" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Middlewares/Third_Party/LoRaWAN/Utilities" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Middlewares/Third_Party/LoRaWAN/Core" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/BSP/Components/Common" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/BSP/Components/hts221" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/BSP/Components/lps22hb" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/BSP/Components/lps25hb" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/BSP/Components/sx1272" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/BSP/X_NUCLEO_IKS01A1" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/BSP/X_NUCLEO_IKS01A2" -I../../../../../../../../Drivers/BSP/sx1272mb2das  -Os -g3 -Wall -fmessage-length=0 -std=c++11 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Middlewares/LoRaWAN/Mac/LoRaMacParser.o: /home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Middlewares/Third_Party/LoRaWAN/Mac/LoRaMacParser.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m0plus -mthumb -mfloat-abi=soft -DSTM32L073xx -DUSE_STM32L0XX_NUCLEO -DUSE_HAL_DRIVER -DREGION_EU868 -DGXX_EXPERIMENTAL_CXX0X -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Projects/STM32L073RZ-Nucleo/Applications/LoRa/End_Node/Core/inc" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Projects/STM32L073RZ-Nucleo/Applications/LoRa/End_Node/LoRaWAN/App/inc" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/BSP/STM32L0xx_Nucleo" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/STM32L0xx_HAL_Driver/Inc" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/CMSIS/Device/ST/STM32L0xx/Include" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/CMSIS/Include" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Middlewares/Third_Party/LoRaWAN/Crypto" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Middlewares/Third_Party/LoRaWAN/Mac" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Middlewares/Third_Party/LoRaWAN/Phy" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Middlewares/Third_Party/LoRaWAN/Utilities" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Middlewares/Third_Party/LoRaWAN/Core" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/BSP/Components/Common" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/BSP/Components/hts221" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/BSP/Components/lps22hb" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/BSP/Components/lps25hb" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/BSP/Components/sx1272" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/BSP/X_NUCLEO_IKS01A1" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/BSP/X_NUCLEO_IKS01A2" -I../../../../../../../../Drivers/BSP/sx1272mb2das  -Os -g3 -Wall -fmessage-length=0 -std=c++11 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Middlewares/LoRaWAN/Mac/LoRaMacSerializer.o: /home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Middlewares/Third_Party/LoRaWAN/Mac/LoRaMacSerializer.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m0plus -mthumb -mfloat-abi=soft -DSTM32L073xx -DUSE_STM32L0XX_NUCLEO -DUSE_HAL_DRIVER -DREGION_EU868 -DGXX_EXPERIMENTAL_CXX0X -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Projects/STM32L073RZ-Nucleo/Applications/LoRa/End_Node/Core/inc" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Projects/STM32L073RZ-Nucleo/Applications/LoRa/End_Node/LoRaWAN/App/inc" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/BSP/STM32L0xx_Nucleo" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/STM32L0xx_HAL_Driver/Inc" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/CMSIS/Device/ST/STM32L0xx/Include" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/CMSIS/Include" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Middlewares/Third_Party/LoRaWAN/Crypto" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Middlewares/Third_Party/LoRaWAN/Mac" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Middlewares/Third_Party/LoRaWAN/Phy" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Middlewares/Third_Party/LoRaWAN/Utilities" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Middlewares/Third_Party/LoRaWAN/Core" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/BSP/Components/Common" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/BSP/Components/hts221" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/BSP/Components/lps22hb" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/BSP/Components/lps25hb" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/BSP/Components/sx1272" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/BSP/X_NUCLEO_IKS01A1" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/BSP/X_NUCLEO_IKS01A2" -I../../../../../../../../Drivers/BSP/sx1272mb2das  -Os -g3 -Wall -fmessage-length=0 -std=c++11 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


