################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal.c \
/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_adc.c \
/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_adc_ex.c \
/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_cortex.c \
/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_dma.c \
/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_gpio.c \
/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_i2c.c \
/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_pwr.c \
/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_pwr_ex.c \
/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_rcc.c \
/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_rcc_ex.c \
/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_rtc.c \
/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_rtc_ex.c \
/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_spi.c \
/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_tim.c \
/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_tim_ex.c \
/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_uart.c \
/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_uart_ex.c 

OBJS += \
./Drivers/STM32L0xx_HAL_Driver/stm32l0xx_hal.o \
./Drivers/STM32L0xx_HAL_Driver/stm32l0xx_hal_adc.o \
./Drivers/STM32L0xx_HAL_Driver/stm32l0xx_hal_adc_ex.o \
./Drivers/STM32L0xx_HAL_Driver/stm32l0xx_hal_cortex.o \
./Drivers/STM32L0xx_HAL_Driver/stm32l0xx_hal_dma.o \
./Drivers/STM32L0xx_HAL_Driver/stm32l0xx_hal_gpio.o \
./Drivers/STM32L0xx_HAL_Driver/stm32l0xx_hal_i2c.o \
./Drivers/STM32L0xx_HAL_Driver/stm32l0xx_hal_pwr.o \
./Drivers/STM32L0xx_HAL_Driver/stm32l0xx_hal_pwr_ex.o \
./Drivers/STM32L0xx_HAL_Driver/stm32l0xx_hal_rcc.o \
./Drivers/STM32L0xx_HAL_Driver/stm32l0xx_hal_rcc_ex.o \
./Drivers/STM32L0xx_HAL_Driver/stm32l0xx_hal_rtc.o \
./Drivers/STM32L0xx_HAL_Driver/stm32l0xx_hal_rtc_ex.o \
./Drivers/STM32L0xx_HAL_Driver/stm32l0xx_hal_spi.o \
./Drivers/STM32L0xx_HAL_Driver/stm32l0xx_hal_tim.o \
./Drivers/STM32L0xx_HAL_Driver/stm32l0xx_hal_tim_ex.o \
./Drivers/STM32L0xx_HAL_Driver/stm32l0xx_hal_uart.o \
./Drivers/STM32L0xx_HAL_Driver/stm32l0xx_hal_uart_ex.o 

C_DEPS += \
./Drivers/STM32L0xx_HAL_Driver/stm32l0xx_hal.d \
./Drivers/STM32L0xx_HAL_Driver/stm32l0xx_hal_adc.d \
./Drivers/STM32L0xx_HAL_Driver/stm32l0xx_hal_adc_ex.d \
./Drivers/STM32L0xx_HAL_Driver/stm32l0xx_hal_cortex.d \
./Drivers/STM32L0xx_HAL_Driver/stm32l0xx_hal_dma.d \
./Drivers/STM32L0xx_HAL_Driver/stm32l0xx_hal_gpio.d \
./Drivers/STM32L0xx_HAL_Driver/stm32l0xx_hal_i2c.d \
./Drivers/STM32L0xx_HAL_Driver/stm32l0xx_hal_pwr.d \
./Drivers/STM32L0xx_HAL_Driver/stm32l0xx_hal_pwr_ex.d \
./Drivers/STM32L0xx_HAL_Driver/stm32l0xx_hal_rcc.d \
./Drivers/STM32L0xx_HAL_Driver/stm32l0xx_hal_rcc_ex.d \
./Drivers/STM32L0xx_HAL_Driver/stm32l0xx_hal_rtc.d \
./Drivers/STM32L0xx_HAL_Driver/stm32l0xx_hal_rtc_ex.d \
./Drivers/STM32L0xx_HAL_Driver/stm32l0xx_hal_spi.d \
./Drivers/STM32L0xx_HAL_Driver/stm32l0xx_hal_tim.d \
./Drivers/STM32L0xx_HAL_Driver/stm32l0xx_hal_tim_ex.d \
./Drivers/STM32L0xx_HAL_Driver/stm32l0xx_hal_uart.d \
./Drivers/STM32L0xx_HAL_Driver/stm32l0xx_hal_uart_ex.d 


# Each subdirectory must supply rules for building sources it contributes
Drivers/STM32L0xx_HAL_Driver/stm32l0xx_hal.o: /home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m0plus -mthumb -mfloat-abi=soft -DSTM32L073xx -DUSE_STM32L0XX_NUCLEO -DUSE_HAL_DRIVER -DREGION_EU868 -DGXX_EXPERIMENTAL_CXX0X -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Projects/STM32L073RZ-Nucleo/Applications/LoRa/End_Node/Core/inc" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Projects/STM32L073RZ-Nucleo/Applications/LoRa/End_Node/LoRaWAN/App/inc" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/BSP/STM32L0xx_Nucleo" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/STM32L0xx_HAL_Driver/Inc" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/CMSIS/Device/ST/STM32L0xx/Include" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/CMSIS/Include" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Middlewares/Third_Party/LoRaWAN/Crypto" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Middlewares/Third_Party/LoRaWAN/Mac" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Middlewares/Third_Party/LoRaWAN/Phy" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Middlewares/Third_Party/LoRaWAN/Utilities" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Middlewares/Third_Party/LoRaWAN/Core" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/BSP/Components/Common" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/BSP/Components/hts221" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/BSP/Components/lps22hb" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/BSP/Components/lps25hb" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/BSP/Components/sx1272" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/BSP/X_NUCLEO_IKS01A1" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/BSP/X_NUCLEO_IKS01A2" -I../../../../../../../../Drivers/BSP/sx1272mb2das  -Os -g3 -Wall -fmessage-length=0 -std=c++11 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Drivers/STM32L0xx_HAL_Driver/stm32l0xx_hal_adc.o: /home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_adc.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m0plus -mthumb -mfloat-abi=soft -DSTM32L073xx -DUSE_STM32L0XX_NUCLEO -DUSE_HAL_DRIVER -DREGION_EU868 -DGXX_EXPERIMENTAL_CXX0X -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Projects/STM32L073RZ-Nucleo/Applications/LoRa/End_Node/Core/inc" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Projects/STM32L073RZ-Nucleo/Applications/LoRa/End_Node/LoRaWAN/App/inc" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/BSP/STM32L0xx_Nucleo" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/STM32L0xx_HAL_Driver/Inc" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/CMSIS/Device/ST/STM32L0xx/Include" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/CMSIS/Include" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Middlewares/Third_Party/LoRaWAN/Crypto" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Middlewares/Third_Party/LoRaWAN/Mac" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Middlewares/Third_Party/LoRaWAN/Phy" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Middlewares/Third_Party/LoRaWAN/Utilities" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Middlewares/Third_Party/LoRaWAN/Core" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/BSP/Components/Common" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/BSP/Components/hts221" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/BSP/Components/lps22hb" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/BSP/Components/lps25hb" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/BSP/Components/sx1272" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/BSP/X_NUCLEO_IKS01A1" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/BSP/X_NUCLEO_IKS01A2" -I../../../../../../../../Drivers/BSP/sx1272mb2das  -Os -g3 -Wall -fmessage-length=0 -std=c++11 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Drivers/STM32L0xx_HAL_Driver/stm32l0xx_hal_adc_ex.o: /home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_adc_ex.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m0plus -mthumb -mfloat-abi=soft -DSTM32L073xx -DUSE_STM32L0XX_NUCLEO -DUSE_HAL_DRIVER -DREGION_EU868 -DGXX_EXPERIMENTAL_CXX0X -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Projects/STM32L073RZ-Nucleo/Applications/LoRa/End_Node/Core/inc" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Projects/STM32L073RZ-Nucleo/Applications/LoRa/End_Node/LoRaWAN/App/inc" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/BSP/STM32L0xx_Nucleo" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/STM32L0xx_HAL_Driver/Inc" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/CMSIS/Device/ST/STM32L0xx/Include" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/CMSIS/Include" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Middlewares/Third_Party/LoRaWAN/Crypto" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Middlewares/Third_Party/LoRaWAN/Mac" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Middlewares/Third_Party/LoRaWAN/Phy" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Middlewares/Third_Party/LoRaWAN/Utilities" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Middlewares/Third_Party/LoRaWAN/Core" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/BSP/Components/Common" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/BSP/Components/hts221" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/BSP/Components/lps22hb" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/BSP/Components/lps25hb" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/BSP/Components/sx1272" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/BSP/X_NUCLEO_IKS01A1" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/BSP/X_NUCLEO_IKS01A2" -I../../../../../../../../Drivers/BSP/sx1272mb2das  -Os -g3 -Wall -fmessage-length=0 -std=c++11 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Drivers/STM32L0xx_HAL_Driver/stm32l0xx_hal_cortex.o: /home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_cortex.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m0plus -mthumb -mfloat-abi=soft -DSTM32L073xx -DUSE_STM32L0XX_NUCLEO -DUSE_HAL_DRIVER -DREGION_EU868 -DGXX_EXPERIMENTAL_CXX0X -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Projects/STM32L073RZ-Nucleo/Applications/LoRa/End_Node/Core/inc" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Projects/STM32L073RZ-Nucleo/Applications/LoRa/End_Node/LoRaWAN/App/inc" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/BSP/STM32L0xx_Nucleo" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/STM32L0xx_HAL_Driver/Inc" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/CMSIS/Device/ST/STM32L0xx/Include" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/CMSIS/Include" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Middlewares/Third_Party/LoRaWAN/Crypto" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Middlewares/Third_Party/LoRaWAN/Mac" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Middlewares/Third_Party/LoRaWAN/Phy" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Middlewares/Third_Party/LoRaWAN/Utilities" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Middlewares/Third_Party/LoRaWAN/Core" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/BSP/Components/Common" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/BSP/Components/hts221" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/BSP/Components/lps22hb" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/BSP/Components/lps25hb" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/BSP/Components/sx1272" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/BSP/X_NUCLEO_IKS01A1" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/BSP/X_NUCLEO_IKS01A2" -I../../../../../../../../Drivers/BSP/sx1272mb2das  -Os -g3 -Wall -fmessage-length=0 -std=c++11 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Drivers/STM32L0xx_HAL_Driver/stm32l0xx_hal_dma.o: /home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_dma.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m0plus -mthumb -mfloat-abi=soft -DSTM32L073xx -DUSE_STM32L0XX_NUCLEO -DUSE_HAL_DRIVER -DREGION_EU868 -DGXX_EXPERIMENTAL_CXX0X -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Projects/STM32L073RZ-Nucleo/Applications/LoRa/End_Node/Core/inc" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Projects/STM32L073RZ-Nucleo/Applications/LoRa/End_Node/LoRaWAN/App/inc" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/BSP/STM32L0xx_Nucleo" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/STM32L0xx_HAL_Driver/Inc" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/CMSIS/Device/ST/STM32L0xx/Include" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/CMSIS/Include" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Middlewares/Third_Party/LoRaWAN/Crypto" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Middlewares/Third_Party/LoRaWAN/Mac" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Middlewares/Third_Party/LoRaWAN/Phy" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Middlewares/Third_Party/LoRaWAN/Utilities" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Middlewares/Third_Party/LoRaWAN/Core" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/BSP/Components/Common" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/BSP/Components/hts221" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/BSP/Components/lps22hb" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/BSP/Components/lps25hb" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/BSP/Components/sx1272" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/BSP/X_NUCLEO_IKS01A1" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/BSP/X_NUCLEO_IKS01A2" -I../../../../../../../../Drivers/BSP/sx1272mb2das  -Os -g3 -Wall -fmessage-length=0 -std=c++11 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Drivers/STM32L0xx_HAL_Driver/stm32l0xx_hal_gpio.o: /home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_gpio.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m0plus -mthumb -mfloat-abi=soft -DSTM32L073xx -DUSE_STM32L0XX_NUCLEO -DUSE_HAL_DRIVER -DREGION_EU868 -DGXX_EXPERIMENTAL_CXX0X -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Projects/STM32L073RZ-Nucleo/Applications/LoRa/End_Node/Core/inc" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Projects/STM32L073RZ-Nucleo/Applications/LoRa/End_Node/LoRaWAN/App/inc" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/BSP/STM32L0xx_Nucleo" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/STM32L0xx_HAL_Driver/Inc" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/CMSIS/Device/ST/STM32L0xx/Include" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/CMSIS/Include" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Middlewares/Third_Party/LoRaWAN/Crypto" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Middlewares/Third_Party/LoRaWAN/Mac" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Middlewares/Third_Party/LoRaWAN/Phy" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Middlewares/Third_Party/LoRaWAN/Utilities" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Middlewares/Third_Party/LoRaWAN/Core" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/BSP/Components/Common" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/BSP/Components/hts221" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/BSP/Components/lps22hb" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/BSP/Components/lps25hb" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/BSP/Components/sx1272" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/BSP/X_NUCLEO_IKS01A1" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/BSP/X_NUCLEO_IKS01A2" -I../../../../../../../../Drivers/BSP/sx1272mb2das  -Os -g3 -Wall -fmessage-length=0 -std=c++11 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Drivers/STM32L0xx_HAL_Driver/stm32l0xx_hal_i2c.o: /home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_i2c.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m0plus -mthumb -mfloat-abi=soft -DSTM32L073xx -DUSE_STM32L0XX_NUCLEO -DUSE_HAL_DRIVER -DREGION_EU868 -DGXX_EXPERIMENTAL_CXX0X -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Projects/STM32L073RZ-Nucleo/Applications/LoRa/End_Node/Core/inc" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Projects/STM32L073RZ-Nucleo/Applications/LoRa/End_Node/LoRaWAN/App/inc" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/BSP/STM32L0xx_Nucleo" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/STM32L0xx_HAL_Driver/Inc" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/CMSIS/Device/ST/STM32L0xx/Include" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/CMSIS/Include" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Middlewares/Third_Party/LoRaWAN/Crypto" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Middlewares/Third_Party/LoRaWAN/Mac" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Middlewares/Third_Party/LoRaWAN/Phy" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Middlewares/Third_Party/LoRaWAN/Utilities" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Middlewares/Third_Party/LoRaWAN/Core" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/BSP/Components/Common" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/BSP/Components/hts221" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/BSP/Components/lps22hb" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/BSP/Components/lps25hb" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/BSP/Components/sx1272" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/BSP/X_NUCLEO_IKS01A1" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/BSP/X_NUCLEO_IKS01A2" -I../../../../../../../../Drivers/BSP/sx1272mb2das  -Os -g3 -Wall -fmessage-length=0 -std=c++11 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Drivers/STM32L0xx_HAL_Driver/stm32l0xx_hal_pwr.o: /home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_pwr.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m0plus -mthumb -mfloat-abi=soft -DSTM32L073xx -DUSE_STM32L0XX_NUCLEO -DUSE_HAL_DRIVER -DREGION_EU868 -DGXX_EXPERIMENTAL_CXX0X -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Projects/STM32L073RZ-Nucleo/Applications/LoRa/End_Node/Core/inc" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Projects/STM32L073RZ-Nucleo/Applications/LoRa/End_Node/LoRaWAN/App/inc" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/BSP/STM32L0xx_Nucleo" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/STM32L0xx_HAL_Driver/Inc" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/CMSIS/Device/ST/STM32L0xx/Include" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/CMSIS/Include" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Middlewares/Third_Party/LoRaWAN/Crypto" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Middlewares/Third_Party/LoRaWAN/Mac" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Middlewares/Third_Party/LoRaWAN/Phy" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Middlewares/Third_Party/LoRaWAN/Utilities" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Middlewares/Third_Party/LoRaWAN/Core" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/BSP/Components/Common" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/BSP/Components/hts221" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/BSP/Components/lps22hb" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/BSP/Components/lps25hb" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/BSP/Components/sx1272" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/BSP/X_NUCLEO_IKS01A1" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/BSP/X_NUCLEO_IKS01A2" -I../../../../../../../../Drivers/BSP/sx1272mb2das  -Os -g3 -Wall -fmessage-length=0 -std=c++11 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Drivers/STM32L0xx_HAL_Driver/stm32l0xx_hal_pwr_ex.o: /home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_pwr_ex.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m0plus -mthumb -mfloat-abi=soft -DSTM32L073xx -DUSE_STM32L0XX_NUCLEO -DUSE_HAL_DRIVER -DREGION_EU868 -DGXX_EXPERIMENTAL_CXX0X -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Projects/STM32L073RZ-Nucleo/Applications/LoRa/End_Node/Core/inc" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Projects/STM32L073RZ-Nucleo/Applications/LoRa/End_Node/LoRaWAN/App/inc" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/BSP/STM32L0xx_Nucleo" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/STM32L0xx_HAL_Driver/Inc" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/CMSIS/Device/ST/STM32L0xx/Include" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/CMSIS/Include" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Middlewares/Third_Party/LoRaWAN/Crypto" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Middlewares/Third_Party/LoRaWAN/Mac" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Middlewares/Third_Party/LoRaWAN/Phy" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Middlewares/Third_Party/LoRaWAN/Utilities" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Middlewares/Third_Party/LoRaWAN/Core" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/BSP/Components/Common" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/BSP/Components/hts221" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/BSP/Components/lps22hb" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/BSP/Components/lps25hb" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/BSP/Components/sx1272" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/BSP/X_NUCLEO_IKS01A1" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/BSP/X_NUCLEO_IKS01A2" -I../../../../../../../../Drivers/BSP/sx1272mb2das  -Os -g3 -Wall -fmessage-length=0 -std=c++11 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Drivers/STM32L0xx_HAL_Driver/stm32l0xx_hal_rcc.o: /home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_rcc.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m0plus -mthumb -mfloat-abi=soft -DSTM32L073xx -DUSE_STM32L0XX_NUCLEO -DUSE_HAL_DRIVER -DREGION_EU868 -DGXX_EXPERIMENTAL_CXX0X -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Projects/STM32L073RZ-Nucleo/Applications/LoRa/End_Node/Core/inc" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Projects/STM32L073RZ-Nucleo/Applications/LoRa/End_Node/LoRaWAN/App/inc" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/BSP/STM32L0xx_Nucleo" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/STM32L0xx_HAL_Driver/Inc" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/CMSIS/Device/ST/STM32L0xx/Include" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/CMSIS/Include" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Middlewares/Third_Party/LoRaWAN/Crypto" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Middlewares/Third_Party/LoRaWAN/Mac" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Middlewares/Third_Party/LoRaWAN/Phy" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Middlewares/Third_Party/LoRaWAN/Utilities" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Middlewares/Third_Party/LoRaWAN/Core" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/BSP/Components/Common" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/BSP/Components/hts221" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/BSP/Components/lps22hb" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/BSP/Components/lps25hb" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/BSP/Components/sx1272" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/BSP/X_NUCLEO_IKS01A1" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/BSP/X_NUCLEO_IKS01A2" -I../../../../../../../../Drivers/BSP/sx1272mb2das  -Os -g3 -Wall -fmessage-length=0 -std=c++11 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Drivers/STM32L0xx_HAL_Driver/stm32l0xx_hal_rcc_ex.o: /home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_rcc_ex.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m0plus -mthumb -mfloat-abi=soft -DSTM32L073xx -DUSE_STM32L0XX_NUCLEO -DUSE_HAL_DRIVER -DREGION_EU868 -DGXX_EXPERIMENTAL_CXX0X -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Projects/STM32L073RZ-Nucleo/Applications/LoRa/End_Node/Core/inc" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Projects/STM32L073RZ-Nucleo/Applications/LoRa/End_Node/LoRaWAN/App/inc" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/BSP/STM32L0xx_Nucleo" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/STM32L0xx_HAL_Driver/Inc" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/CMSIS/Device/ST/STM32L0xx/Include" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/CMSIS/Include" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Middlewares/Third_Party/LoRaWAN/Crypto" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Middlewares/Third_Party/LoRaWAN/Mac" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Middlewares/Third_Party/LoRaWAN/Phy" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Middlewares/Third_Party/LoRaWAN/Utilities" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Middlewares/Third_Party/LoRaWAN/Core" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/BSP/Components/Common" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/BSP/Components/hts221" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/BSP/Components/lps22hb" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/BSP/Components/lps25hb" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/BSP/Components/sx1272" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/BSP/X_NUCLEO_IKS01A1" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/BSP/X_NUCLEO_IKS01A2" -I../../../../../../../../Drivers/BSP/sx1272mb2das  -Os -g3 -Wall -fmessage-length=0 -std=c++11 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Drivers/STM32L0xx_HAL_Driver/stm32l0xx_hal_rtc.o: /home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_rtc.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m0plus -mthumb -mfloat-abi=soft -DSTM32L073xx -DUSE_STM32L0XX_NUCLEO -DUSE_HAL_DRIVER -DREGION_EU868 -DGXX_EXPERIMENTAL_CXX0X -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Projects/STM32L073RZ-Nucleo/Applications/LoRa/End_Node/Core/inc" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Projects/STM32L073RZ-Nucleo/Applications/LoRa/End_Node/LoRaWAN/App/inc" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/BSP/STM32L0xx_Nucleo" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/STM32L0xx_HAL_Driver/Inc" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/CMSIS/Device/ST/STM32L0xx/Include" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/CMSIS/Include" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Middlewares/Third_Party/LoRaWAN/Crypto" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Middlewares/Third_Party/LoRaWAN/Mac" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Middlewares/Third_Party/LoRaWAN/Phy" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Middlewares/Third_Party/LoRaWAN/Utilities" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Middlewares/Third_Party/LoRaWAN/Core" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/BSP/Components/Common" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/BSP/Components/hts221" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/BSP/Components/lps22hb" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/BSP/Components/lps25hb" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/BSP/Components/sx1272" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/BSP/X_NUCLEO_IKS01A1" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/BSP/X_NUCLEO_IKS01A2" -I../../../../../../../../Drivers/BSP/sx1272mb2das  -Os -g3 -Wall -fmessage-length=0 -std=c++11 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Drivers/STM32L0xx_HAL_Driver/stm32l0xx_hal_rtc_ex.o: /home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_rtc_ex.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m0plus -mthumb -mfloat-abi=soft -DSTM32L073xx -DUSE_STM32L0XX_NUCLEO -DUSE_HAL_DRIVER -DREGION_EU868 -DGXX_EXPERIMENTAL_CXX0X -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Projects/STM32L073RZ-Nucleo/Applications/LoRa/End_Node/Core/inc" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Projects/STM32L073RZ-Nucleo/Applications/LoRa/End_Node/LoRaWAN/App/inc" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/BSP/STM32L0xx_Nucleo" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/STM32L0xx_HAL_Driver/Inc" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/CMSIS/Device/ST/STM32L0xx/Include" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/CMSIS/Include" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Middlewares/Third_Party/LoRaWAN/Crypto" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Middlewares/Third_Party/LoRaWAN/Mac" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Middlewares/Third_Party/LoRaWAN/Phy" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Middlewares/Third_Party/LoRaWAN/Utilities" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Middlewares/Third_Party/LoRaWAN/Core" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/BSP/Components/Common" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/BSP/Components/hts221" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/BSP/Components/lps22hb" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/BSP/Components/lps25hb" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/BSP/Components/sx1272" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/BSP/X_NUCLEO_IKS01A1" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/BSP/X_NUCLEO_IKS01A2" -I../../../../../../../../Drivers/BSP/sx1272mb2das  -Os -g3 -Wall -fmessage-length=0 -std=c++11 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Drivers/STM32L0xx_HAL_Driver/stm32l0xx_hal_spi.o: /home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_spi.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m0plus -mthumb -mfloat-abi=soft -DSTM32L073xx -DUSE_STM32L0XX_NUCLEO -DUSE_HAL_DRIVER -DREGION_EU868 -DGXX_EXPERIMENTAL_CXX0X -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Projects/STM32L073RZ-Nucleo/Applications/LoRa/End_Node/Core/inc" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Projects/STM32L073RZ-Nucleo/Applications/LoRa/End_Node/LoRaWAN/App/inc" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/BSP/STM32L0xx_Nucleo" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/STM32L0xx_HAL_Driver/Inc" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/CMSIS/Device/ST/STM32L0xx/Include" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/CMSIS/Include" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Middlewares/Third_Party/LoRaWAN/Crypto" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Middlewares/Third_Party/LoRaWAN/Mac" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Middlewares/Third_Party/LoRaWAN/Phy" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Middlewares/Third_Party/LoRaWAN/Utilities" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Middlewares/Third_Party/LoRaWAN/Core" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/BSP/Components/Common" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/BSP/Components/hts221" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/BSP/Components/lps22hb" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/BSP/Components/lps25hb" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/BSP/Components/sx1272" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/BSP/X_NUCLEO_IKS01A1" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/BSP/X_NUCLEO_IKS01A2" -I../../../../../../../../Drivers/BSP/sx1272mb2das  -Os -g3 -Wall -fmessage-length=0 -std=c++11 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Drivers/STM32L0xx_HAL_Driver/stm32l0xx_hal_tim.o: /home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_tim.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m0plus -mthumb -mfloat-abi=soft -DSTM32L073xx -DUSE_STM32L0XX_NUCLEO -DUSE_HAL_DRIVER -DREGION_EU868 -DGXX_EXPERIMENTAL_CXX0X -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Projects/STM32L073RZ-Nucleo/Applications/LoRa/End_Node/Core/inc" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Projects/STM32L073RZ-Nucleo/Applications/LoRa/End_Node/LoRaWAN/App/inc" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/BSP/STM32L0xx_Nucleo" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/STM32L0xx_HAL_Driver/Inc" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/CMSIS/Device/ST/STM32L0xx/Include" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/CMSIS/Include" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Middlewares/Third_Party/LoRaWAN/Crypto" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Middlewares/Third_Party/LoRaWAN/Mac" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Middlewares/Third_Party/LoRaWAN/Phy" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Middlewares/Third_Party/LoRaWAN/Utilities" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Middlewares/Third_Party/LoRaWAN/Core" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/BSP/Components/Common" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/BSP/Components/hts221" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/BSP/Components/lps22hb" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/BSP/Components/lps25hb" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/BSP/Components/sx1272" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/BSP/X_NUCLEO_IKS01A1" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/BSP/X_NUCLEO_IKS01A2" -I../../../../../../../../Drivers/BSP/sx1272mb2das  -Os -g3 -Wall -fmessage-length=0 -std=c++11 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Drivers/STM32L0xx_HAL_Driver/stm32l0xx_hal_tim_ex.o: /home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_tim_ex.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m0plus -mthumb -mfloat-abi=soft -DSTM32L073xx -DUSE_STM32L0XX_NUCLEO -DUSE_HAL_DRIVER -DREGION_EU868 -DGXX_EXPERIMENTAL_CXX0X -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Projects/STM32L073RZ-Nucleo/Applications/LoRa/End_Node/Core/inc" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Projects/STM32L073RZ-Nucleo/Applications/LoRa/End_Node/LoRaWAN/App/inc" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/BSP/STM32L0xx_Nucleo" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/STM32L0xx_HAL_Driver/Inc" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/CMSIS/Device/ST/STM32L0xx/Include" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/CMSIS/Include" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Middlewares/Third_Party/LoRaWAN/Crypto" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Middlewares/Third_Party/LoRaWAN/Mac" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Middlewares/Third_Party/LoRaWAN/Phy" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Middlewares/Third_Party/LoRaWAN/Utilities" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Middlewares/Third_Party/LoRaWAN/Core" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/BSP/Components/Common" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/BSP/Components/hts221" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/BSP/Components/lps22hb" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/BSP/Components/lps25hb" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/BSP/Components/sx1272" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/BSP/X_NUCLEO_IKS01A1" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/BSP/X_NUCLEO_IKS01A2" -I../../../../../../../../Drivers/BSP/sx1272mb2das  -Os -g3 -Wall -fmessage-length=0 -std=c++11 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Drivers/STM32L0xx_HAL_Driver/stm32l0xx_hal_uart.o: /home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_uart.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m0plus -mthumb -mfloat-abi=soft -DSTM32L073xx -DUSE_STM32L0XX_NUCLEO -DUSE_HAL_DRIVER -DREGION_EU868 -DGXX_EXPERIMENTAL_CXX0X -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Projects/STM32L073RZ-Nucleo/Applications/LoRa/End_Node/Core/inc" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Projects/STM32L073RZ-Nucleo/Applications/LoRa/End_Node/LoRaWAN/App/inc" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/BSP/STM32L0xx_Nucleo" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/STM32L0xx_HAL_Driver/Inc" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/CMSIS/Device/ST/STM32L0xx/Include" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/CMSIS/Include" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Middlewares/Third_Party/LoRaWAN/Crypto" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Middlewares/Third_Party/LoRaWAN/Mac" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Middlewares/Third_Party/LoRaWAN/Phy" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Middlewares/Third_Party/LoRaWAN/Utilities" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Middlewares/Third_Party/LoRaWAN/Core" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/BSP/Components/Common" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/BSP/Components/hts221" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/BSP/Components/lps22hb" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/BSP/Components/lps25hb" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/BSP/Components/sx1272" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/BSP/X_NUCLEO_IKS01A1" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/BSP/X_NUCLEO_IKS01A2" -I../../../../../../../../Drivers/BSP/sx1272mb2das  -Os -g3 -Wall -fmessage-length=0 -std=c++11 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Drivers/STM32L0xx_HAL_Driver/stm32l0xx_hal_uart_ex.o: /home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_uart_ex.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m0plus -mthumb -mfloat-abi=soft -DSTM32L073xx -DUSE_STM32L0XX_NUCLEO -DUSE_HAL_DRIVER -DREGION_EU868 -DGXX_EXPERIMENTAL_CXX0X -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Projects/STM32L073RZ-Nucleo/Applications/LoRa/End_Node/Core/inc" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Projects/STM32L073RZ-Nucleo/Applications/LoRa/End_Node/LoRaWAN/App/inc" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/BSP/STM32L0xx_Nucleo" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/STM32L0xx_HAL_Driver/Inc" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/CMSIS/Device/ST/STM32L0xx/Include" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/CMSIS/Include" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Middlewares/Third_Party/LoRaWAN/Crypto" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Middlewares/Third_Party/LoRaWAN/Mac" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Middlewares/Third_Party/LoRaWAN/Phy" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Middlewares/Third_Party/LoRaWAN/Utilities" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Middlewares/Third_Party/LoRaWAN/Core" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/BSP/Components/Common" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/BSP/Components/hts221" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/BSP/Components/lps22hb" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/BSP/Components/lps25hb" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/BSP/Components/sx1272" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/BSP/X_NUCLEO_IKS01A1" -I"/home/ibraheem/Downloads/jeriess/STM32CubeExpansion_LRWAN_V1.2.0/Drivers/BSP/X_NUCLEO_IKS01A2" -I../../../../../../../../Drivers/BSP/sx1272mb2das  -Os -g3 -Wall -fmessage-length=0 -std=c++11 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


